from __future__ import annotations

import io
import json
import zipfile

from pydantic import BaseModel

from .analysis_models import (
    ArtifactKind,
    Chapter,
    InteractiveGuide,
    MindMap,
    SummaryContent,
    VisualStory,
    WebsiteManifest,
    WebsiteTheme,
)
from .transcripts import TranscriptDocument
from .website_renderer import render_website_html


def export_json(payload: BaseModel | list[BaseModel]) -> str:
    if isinstance(payload, list):
        value = [item.model_dump(mode="json") for item in payload]
    else:
        value = payload.model_dump(mode="json")
    return json.dumps(value, ensure_ascii=False, indent=2)


def export_markdown(kind: ArtifactKind, payload: object) -> str:
    if kind == ArtifactKind.SUMMARY and isinstance(payload, SummaryContent):
        sections = [
            "# Summary",
            f"## TL;DR\n\n{payload.tldr.text}",
            f"## Overview\n\n{payload.overview.text}",
            "## Key Takeaways\n\n"
            + "\n".join(f"- {item.text}" for item in payload.key_takeaways),
            "## Important Facts\n\n"
            + "\n".join(f"- {item.statement.text}" for item in payload.important_facts),
            "## Conclusions\n\n"
            + "\n".join(f"- {item.text}" for item in payload.conclusions),
            "## Suggested Questions\n\n"
            + "\n".join(f"- {item.question}" for item in payload.suggested_questions),
        ]
        return "\n\n".join(sections)
    if kind == ArtifactKind.CHAPTERS and isinstance(payload, list):
        chapters = [item for item in payload if isinstance(item, Chapter)]
        return "# Chapter Breakdown\n\n" + "\n\n".join(
            (
                f"## {chapter.start_seconds:.0f}s — {chapter.title}\n\n"
                f"{chapter.summary.text}\n\n"
                + "\n".join(f"- {point.text}" for point in chapter.key_points)
            )
            for chapter in chapters
        )
    if kind == ArtifactKind.MIND_MAP and isinstance(payload, MindMap):
        nodes = {node.id: node for node in payload.nodes}

        def render(node_id: str, depth: int) -> list[str]:
            node = nodes[node_id]
            lines = [f"{'  ' * depth}- {node.label}: {node.description}"]
            for child in node.children:
                lines.extend(render(child, depth + 1))
            return lines

        return "# Mind Map\n\n" + "\n".join(render(payload.root_id, 0))
    if kind == ArtifactKind.VISUAL_STORY and isinstance(payload, VisualStory):
        return f"# {payload.title}\n\n" + "\n\n".join(
            f"## {frame.timestamp_seconds:.0f}s — {frame.title}\n\n{frame.narrative}"
            for frame in payload.frames
        )
    if kind == ArtifactKind.INTERACTIVE_GUIDE and isinstance(
        payload, InteractiveGuide
    ):
        return f"# {payload.title}\n\n" + "\n\n".join(
            (
                f"## {step.title}\n\n{step.explanation.text}\n\n"
                f"**Action:** {step.action.instruction}\n\n"
                f"**Checkpoint:** {step.checkpoint.prompt}"
            )
            for step in payload.steps
        )
    if kind == ArtifactKind.TRANSCRIPT and isinstance(payload, TranscriptDocument):
        return "# Transcript\n\n" + "\n\n".join(
            f"**{segment.start:.1f}s–{segment.end:.1f}s** {segment.text}"
            for segment in payload.segments
        )
    if kind == ArtifactKind.DYNAMIC_WEBSITE and isinstance(payload, WebsiteManifest):
        return f"# {payload.title}\n\n{payload.subtitle}\n\n" + "\n\n".join(
            f"## {chapter.title}\n\n{chapter.summary.text}"
            for chapter in payload.chapters
        )
    raise ValueError("This artifact does not support Markdown export")


def export_website_zip(
    manifest: WebsiteManifest,
    *,
    theme: WebsiteTheme | None = None,
) -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("index.html", render_website_html(manifest, theme=theme))
        archive.writestr("manifest.json", export_json(manifest))
        archive.writestr(
            "README.txt",
            "Generated by Bubble Video AI. This package contains no server credentials, "
            "private media, scripts, iframes, or internal API addresses.\n",
        )
    return buffer.getvalue()
